# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
      - libudunits2-dev


r:
 - release

r_packages:
  - covr

# only report coverage after build is successful
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'